# Your Title Here

**Name(s)**: (your name(s) here)

**Website Link**: (your website link)

In [173]:
# !pip install tabulate

In [174]:
import pandas as pd
import numpy as np
from pathlib import Path

import plotly.express as px
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error
import tabulate

pd.options.plotting.backend = "plotly"

# from dsc80_utils import * # Feel free to uncomment and use this.

In [175]:
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 500)
pd.set_option("display.max_colwidth", 200)

In [176]:
df = pd.read_excel(Path("data", "outage.xlsx"))
df.head(10)

,Major power outage events in the continental U.S.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56
0,Time period: January 2000 - July 2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Regions affected: Outages reported in this data file affected a single U.S. state at the time of occurrence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,variables,OBS,YEAR,MONTH,U.S._STATE,POSTAL.CODE,NERC.REGION,CLIMATE.REGION,ANOMALY.LEVEL,CLIMATE.CATEGORY,OUTAGE.START.DATE,OUTAGE.START.TIME,OUTAGE.RESTORATION.DATE,OUTAGE.RESTORATION.TIME,CAUSE.CATEGORY,CAUSE.CATEGORY.DETAIL,HURRICANE.NAMES,OUTAGE.DURATION,DEMAND.LOSS.MW,CUSTOMERS.AFFECTED,RES.PRICE,COM.PRICE,IND.PRICE,TOTAL.PRICE,RES.SALES,COM.SALES,IND.SALES,TOTAL.SALES,RES.PERCEN,COM.PERCEN,IND.PERCEN,RES.CUSTOMERS,COM.CUSTOMERS,IND.CUSTOMERS,TOTAL.CUSTOMERS,RES.CUST.PCT,COM.CUST.PCT,IND.CUST.PCT,PC.REALGSP.STATE,PC.REALGSP.USA,PC.REALGSP.REL,PC.REALGSP.CHANGE,UTIL.REALGSP,TOTAL.REALGSP,UTIL.CONTRI,PI.UTIL.OFUSA,POPULATION,POPPCT_URBAN,POPPCT_UC,POPDEN_URBAN,POPDEN_UC,POPDEN_RURAL,AREAPCT_URBAN,AREAPCT_UC,PCT_LAND,PCT_WATER_TOT,PCT_WATER_INLAND
5,Units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,numeric,NaN,"Day of the week, Month Day, Year",Hour:Minute:Second (AM / PM),"Day of the week, Month Day, Year",Hour:Minute:Second (AM / PM),NaN,NaN,NaN,mins,Megawatt,NaN,cents / kilowatt-hour,cents / kilowatt-hour,cents / kilowatt-hour,cents / kilowatt-hour,Megawatt-hour,Megawatt-hour,Megawatt-hour,Megawatt-hour,%,%,%,NaN,NaN,NaN,NaN,%,%,%,USD,USD,fraction,%,USD,USD,%,%,NaN,%,%,persons per square mile,persons per square mile,persons per square mile,%,%,%,%,%
6,NaN,1,2011,7,Minnesota,MN,MRO,East North Central,-0.3,normal,2011-07-01 00:00:00,17:00:00,2011-07-03 00:00:00,20:00:00,severe weather,NaN,NaN,3060,NaN,70000,11.6,9.18,6.81,9.28,2332915,2114774,2113291,6562520,35.549073,32.225029,32.202431,2308736,276286,10673,2595696,88.944776,10.644005,0.411181,51268,47586,1.077376,1.6,4802,274182,1.751391,2.2,5348119,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
7,NaN,2,2014,5,Minnesota,MN,MRO,East North Central,-0.1,normal,2014-05-11 00:00:00,18:38:00,2014-05-11 00:00:00,18:39:00,intentional attack,vandalism,NaN,1,NaN,NaN,12.12,9.71,6.49,9.28,1586986,1807756,1887927,5284231,30.032487,34.210389,35.727564,2345860,284978,9898,2640737,88.833534,10.791609,0.37482,53499,49091,1.089792,1.9,5226,291955,1.790002,2.2,5457125,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
8,NaN,3,2010,10,Minnesota,MN,MRO,East North Central,-1.5,cold,2010-10-26 00:00:00,20:00:00,2010-10-28 00:00:00,22:00:00,severe weather,heavy wind,NaN,3000,NaN,70000,10.87,8.19,6.07,8.15,1467293,1801683,1951295,5222116,28.097672,34.501015,37.365983,2300291,276463,10150,2586905,88.920583,10.687018,0.392361,50447,47287,1.066826,2.7,4571,267895,1.706266,2.1,5310903,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
9,NaN,4,2012,6,Minnesota,MN,MRO,East North Central,-0.1,normal,2012-06-19 00:00:00,04:30:00,2012-06-20 00:00:00,23:00:00,severe weather,thunderstorm,NaN,2550,NaN,68200,11.79,9.25,6.71,9.19,1851519,1941174,1993026,5787064,31.994099,33.54333,34.439329,2317336,278466,11010,2606813,88.895368,10.682239,0.422355,51598,48156,1.071476,0.6,5364,277627,1.932089,2.2,5380443,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743

In [177]:
df = df.iloc[4:, 1:].reset_index(drop=True)
df.head()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56
0,OBS,YEAR,MONTH,U.S._STATE,POSTAL.CODE,NERC.REGION,CLIMATE.REGION,ANOMALY.LEVEL,CLIMATE.CATEGORY,OUTAGE.START.DATE,OUTAGE.START.TIME,OUTAGE.RESTORATION.DATE,OUTAGE.RESTORATION.TIME,CAUSE.CATEGORY,CAUSE.CATEGORY.DETAIL,HURRICANE.NAMES,OUTAGE.DURATION,DEMAND.LOSS.MW,CUSTOMERS.AFFECTED,RES.PRICE,COM.PRICE,IND.PRICE,TOTAL.PRICE,RES.SALES,COM.SALES,IND.SALES,TOTAL.SALES,RES.PERCEN,COM.PERCEN,IND.PERCEN,RES.CUSTOMERS,COM.CUSTOMERS,IND.CUSTOMERS,TOTAL.CUSTOMERS,RES.CUST.PCT,COM.CUST.PCT,IND.CUST.PCT,PC.REALGSP.STATE,PC.REALGSP.USA,PC.REALGSP.REL,PC.REALGSP.CHANGE,UTIL.REALGSP,TOTAL.REALGSP,UTIL.CONTRI,PI.UTIL.OFUSA,POPULATION,POPPCT_URBAN,POPPCT_UC,POPDEN_URBAN,POPDEN_UC,POPDEN_RURAL,AREAPCT_URBAN,AREAPCT_UC,PCT_LAND,PCT_WATER_TOT,PCT_WATER_INLAND
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,numeric,NaN,"Day of the week, Month Day, Year",Hour:Minute:Second (AM / PM),"Day of the week, Month Day, Year",Hour:Minute:Second (AM / PM),NaN,NaN,NaN,mins,Megawatt,NaN,cents / kilowatt-hour,cents / kilowatt-hour,cents / kilowatt-hour,cents / kilowatt-hour,Megawatt-hour,Megawatt-hour,Megawatt-hour,Megawatt-hour,%,%,%,NaN,NaN,NaN,NaN,%,%,%,USD,USD,fraction,%,USD,USD,%,%,NaN,%,%,persons per square mile,persons per square mile,persons per square mile,%,%,%,%,%
2,1,2011,7,Minnesota,MN,MRO,East North Central,-0.3,normal,2011-07-01 00:00:00,17:00:00,2011-07-03 00:00:00,20:00:00,severe weather,NaN,NaN,3060,NaN,70000,11.6,9.18,6.81,9.28,2332915,2114774,2113291,6562520,35.549073,32.225029,32.202431,2308736,276286,10673,2595696,88.944776,10.644005,0.411181,51268,47586,1.077376,1.6,4802,274182,1.751391,2.2,5348119,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
3,2,2014,5,Minnesota,MN,MRO,East North Central,-0.1,normal,2014-05-11 00:00:00,18:38:00,2014-05-11 00:00:00,18:39:00,intentional attack,vandalism,NaN,1,NaN,NaN,12.12,9.71,6.49,9.28,1586986,1807756,1887927,5284231,30.032487,34.210389,35.727564,2345860,284978,9898,2640737,88.833534,10.791609,0.37482,53499,49091,1.089792,1.9,5226,291955,1.790002,2.2,5457125,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
4,3,2010,10,Minnesota,MN,MRO,East North Central,-1.5,cold,2010-10-26 00:00:00,20:00:00,2010-10-28 00:00:00,22:00:00,severe weather,heavy wind,NaN,3000,NaN,70000,10.87,8.19,6.07,8.15,1467293,1801683,1951295,5222116,28.097672,34.501015,37.365983,2300291,276463,10150,2586905,88.920583,10.687018,0.392361,50447,47287,1.066826,2.7,4571,267895,1.706266,2.1,5310903,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743

In [178]:
mapping_dict = {key: "" for key in df.iloc[1].unique()}
mapping_dict["cents / kilowatt-hour"] = "(cents / kWh)"
mapping_dict["USD"] = "($)"
mapping_dict["persons per square mile"] = "(people / sq mi)"
mapping_dict["%"] = "(%)"
df.iloc[0] = df.iloc[0].str.replace(".", "_").str.capitalize()
df.iloc[1] = df.iloc[1].map(mapping_dict)
df.iloc[0] = df.iloc[0].astype(str) + " " + df.iloc[1].astype(str)
df.columns = df.iloc[0].str.strip()
df = df.iloc[2:].set_index("Obs", drop=True)
df = df.rename(columns={"U_s__state": "US_state"})
df.head()

,Year,Month,US_state,Postal_code,Nerc_region,Climate_region,Anomaly_level,Climate_category,Outage_start_date,Outage_start_time,Outage_restoration_date,Outage_restoration_time,Cause_category,Cause_category_detail,Hurricane_names,Outage_duration,Demand_loss_mw,Customers_affected,Res_price (cents / kWh),Com_price (cents / kWh),Ind_price (cents / kWh),Total_price (cents / kWh),Res_sales,Com_sales,Ind_sales,Total_sales,Res_percen (%),Com_percen (%),Ind_percen (%),Res_customers,Com_customers,Ind_customers,Total_customers,Res_cust_pct (%),Com_cust_pct (%),Ind_cust_pct (%),Pc_realgsp_state ($),Pc_realgsp_usa ($),Pc_realgsp_rel,Pc_realgsp_change (%),Util_realgsp ($),Total_realgsp ($),Util_contri (%),Pi_util_ofusa (%),Population,Poppct_urban (%),Poppct_uc (%),Popden_urban (people / sq mi),Popden_uc (people / sq mi),Popden_rural (people / sq mi),Areapct_urban (%),Areapct_uc (%),Pct_land (%),Pct_water_tot (%),Pct_water_inland (%)
Obs,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2011,7,Minnesota,MN,MRO,East North Central,-0.3,normal,2011-07-01 00:00:00,17:00:00,2011-07-03 00:00:00,20:00:00,severe weather,NaN,NaN,3060,NaN,70000,11.6,9.18,6.81,9.28,2332915,2114774,2113291,6562520,35.549073,32.225029,32.202431,2308736,276286,10673,2595696,88.944776,10.644005,0.411181,51268,47586,1.077376,1.6,4802,274182,1.751391,2.2,5348119,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
2,2014,5,Minnesota,MN,MRO,East North Central,-0.1,normal,2014-05-11 00:00:00,18:38:00,2014-05-11 00:00:00,18:39:00,intentional attack,vandalism,NaN,1,NaN,NaN,12.12,9.71,6.49,9.28,1586986,1807756,1887927,5284231,30.032487,34.210389,35.727564,2345860,284978,9898,2640737,88.833534,10.791609,0.37482,53499,49091,1.089792,1.9,5226,291955,1.790002,2.2,5457125,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
3,2010,10,Minnesota,MN,MRO,East North Central,-1.5,cold,2010-10-26 00:00:00,20:00:00,2010-10-28 00:00:00,22:00:00,severe weather,heavy wind,NaN,3000,NaN,70000,10.87,8.19,6.07,8.15,1467293,1801683,1951295,5222116,28.097672,34.501015,37.365983,2300291,276463,10150,2586905,88.920583,10.687018,0.392361,50447,47287,1.066826,2.7,4571,267895,1.706266,2.1,5310903,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
4,2012,6,Minnesota,MN,MRO,East North Central,-0.1,normal,2012-06-19 00:00:00,04:30:00,2012-06-20 00:00:00,23:00:00,severe weather,thunderstorm,NaN,2550,NaN,68200,11.79,9.25,6.71,9.19,1851519,1941174,1993026,5787064,31.994099,33.54333,34.439329,2317336,278466,11010,2606813,88.895368,10.682239,0.422355,51598,48156,1.071476,0.6,5364,277627,1.932089,2.2,5380443,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743
5,2015,7,Minnesota,MN,MRO,East North Central,1.2,warm,2015-07-18 00:00:00,02:00:00,2015-07-19 00:00:00,07:00:00,severe weather,NaN,NaN,1740,250,250000,13.07,10.16,7.74,10.43,2028875,2161612,1777937,5970339,33.982576,36.20585,29.779498,2374674,289044,9812,2673531,88.821637,10.81132,0.367005,54431,49844,1.092027,1.7,4873,292023,1.668704,2.2,5489594,73.27,15.28,2279,1700.5,18.2,2.14,0.6,91.592666,8.407334,5.478743

In [179]:
df.describe()

/var/folders/_h/6x5r9mdd0j5fcx_dg0yzyh9w0000gn/T/ipykernel_62489/3627053830.py:1: FutureWarning:

The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`

/var/folders/_h/6x5r9mdd0j5fcx_dg0yzyh9w0000gn/T/ipykernel_62489/3627053830.py:1: FutureWarning:

The behavior of value_counts with object-dtype is deprecated. In a future version, this will *not* perform dtype inference on the resulting index. To retain the old behavior, use `result.index = result.index.infer_objects()`

,Year,Month,US_state,Postal_code,Nerc_region,Climate_region,Anomaly_level,Climate_category,Outage_start_date,Outage_start_time,Outage_restoration_date,Outage_restoration_time,Cause_category,Cause_category_detail,Hurricane_names,Outage_duration,Demand_loss_mw,Customers_affected,Res_price (cents / kWh),Com_price (cents / kWh),Ind_price (cents / kWh),Total_price (cents / kWh),Res_sales,Com_sales,Ind_sales,Total_sales,Res_percen (%),Com_percen (%),Ind_percen (%),Res_customers,Com_customers,Ind_customers,Total_customers,Res_cust_pct (%),Com_cust_pct (%),Ind_cust_pct (%),Pc_realgsp_state ($),Pc_realgsp_usa ($),Pc_realgsp_rel,Pc_realgsp_change (%),Util_realgsp ($),Total_realgsp ($),Util_contri (%),Pi_util_ofusa (%),Population,Poppct_urban (%),Poppct_uc (%),Popden_urban (people / sq mi),Popden_uc (people / sq mi),Popden_rural (people / sq mi),Areapct_urban (%),Areapct_uc (%),Pct_land (%),Pct_water_tot (%),Pct_water_inland (%)
count,1534,1525,1534,1534,1534,1528,1525.0,1525,1525,1525,1476,1476,1534,1063,72,1476,829,1091,1512.00,1512.00,1512.00,1512.00,1512,1512,1512,1512,1512.000000,1512.000000,1512.000000,1534,1534,1534,1534,1534.000000,1534.000000,1534.000000,1534,1534,1534.000000,1534.0,1534,1534,1534.000000,1534.0,1534,1534.00,1534.00,1534.0,1524.0,1524.0,1534.00,1534.00,1534.000000,1534.000000,1534.000000
unique,17,12,50,50,14,9,36.0,3,1028,622,1100,557,7,52,22,852,282,569,647.00,582.00,542.00,623.00,979,979,979,979,979.000000,979.000000,979.000000,405,405,393,405,405.000000,405.000000,405.000000,402,17,404.000000,95.0,396,405,405.000000,75.0,405,50.00,50.00,50.0,49.0,47.0,46.00,46.00,50.000000,50.000000,50.000000
top,2011,6,California,CA,WECC,Northeast,-0.3,normal,2012-10-29 00:00:00,15:00:00,2011-08-29 00:00:00,12:00:00,severe weather,vandalism,Sandy,1,0,0,14.27,13.49,5.85,8.86,1726552,2344747,340510,4452722,38.775203,52.658733,7.647232,2837631,354185,27845,3219667,88.134301,11.000672,0.864841,52822,47586,1.110032,1.5,3832,360358,1.063387,2.2,6823229,94.95,5.22,4303.7,2124.1,12.7,5.28,0.59,95.164177,4.835823,1.730658
freq,269,195,210,210,451,350,191.0,744,19,35,8,74,763,335,17,97,196,212,11.00,12.00,18.00,11.00,8,8,8,8,8.000000,8.000000,8.000000,29,29,29,29,29.000000,29.000000,29.000000,29,269,29.000000,65.0,29,29,29.000000,92.0,29,210.00,210.00,210.0,210.0,210.0,210.00,210.00,210.000000,210.000000,210.000000

In [180]:
df.isna().sum()

0
Year                                0
Month                               9
US_state                            0
Postal_code                         0
Nerc_region                         0
Climate_region                      6
Anomaly_level                       9
Climate_category                    9
Outage_start_date                   9
Outage_start_time                   9
Outage_restoration_date            58
Outage_restoration_time            58
Cause_category                      0
Cause_category_detail             471
Hurricane_names                  1462
Outage_duration                    58
Demand_loss_mw                    705
Customers_affected                443
Res_price (cents / kWh)            22
Com_price (cents / kWh)            22
Ind_price (cents / kWh)            22
Total_price (cents / kWh)          22
Res_sales                          22
Com_sales                          22
Ind_sales                          22
Total_sales                        22
Res_percen (%)                     22
Com_percen (%)                     22
Ind_percen (%)                     22
Res_customers                       0
Com_customers                       0
Ind_customers                       0
Total_customers                     0
Res_cust_pct (%)                    0
Com_cust_pct (%)                    0
Ind_cust_pct (%)                    0
Pc_realgsp_state ($)                0
Pc_realgsp_usa ($)                  0
Pc_realgsp_rel                      0
Pc_realgsp_change (%)               0
Util_realgsp ($)                    0
Total_realgsp ($)                   0
Util_contri (%)                     0
Pi_util_ofusa (%)                   0
Population                          0
Poppct_urban (%)                    0
Poppct_uc (%)                       0
Popden_urban (people / sq mi)       0
Popden_uc (people / sq mi)         10
Popden_rural (people / sq mi)      10
Areapct_urban (%)                   0
Areapct_uc (%)                      0
Pct_land (%)                        0
Pct_water_tot (%)                   0
Pct_water_inland (%)                0
dtype: int64

In [181]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1534 entries, 1 to 1534
Data columns (total 55 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Year                           1534 non-null   object
 1   Month                          1525 non-null   object
 2   US_state                       1534 non-null   object
 3   Postal_code                    1534 non-null   object
 4   Nerc_region                    1534 non-null   object
 5   Climate_region                 1528 non-null   object
 6   Anomaly_level                  1525 non-null   object
 7   Climate_category               1525 non-null   object
 8   Outage_start_date              1525 non-null   object
 9   Outage_start_time              1525 non-null   object
 10  Outage_restoration_date        1476 non-null   object
 11  Outage_restoration_time        1476 non-null   object
 12  Cause_category                 1534 non-null   object
 13  Cause_category_detail          1063 non-null   object
 14  Hurricane_names                72 non-null     object
 15  Outage_duration                1476 non-null   object
 16  Demand_loss_mw                 829 non-null    object
 17  Customers_affected             1091 non-null   object
 18  Res_price (cents / kWh)        1512 non-null   object
 19  Com_price (cents / kWh)        1512 non-null   object
 20  Ind_price (cents / kWh)        1512 non-null   object
 21  Total_price (cents / kWh)      1512 non-null   object
 22  Res_sales                      1512 non-null   object
 23  Com_sales                      1512 non-null   object
 24  Ind_sales                      1512 non-null   object
 25  Total_sales                    1512 non-null   object
 26  Res_percen (%)                 1512 non-null   object
 27  Com_percen (%)                 1512 non-null   object
 28  Ind_percen (%)                 1512 non-null   object
 29  Res_customers                  1534 non-null   object
 30  Com_customers                  1534 non-null   object
 31  Ind_customers                  1534 non-null   object
 32  Total_customers                1534 non-null   object
 33  Res_cust_pct (%)               1534 non-null   object
 34  Com_cust_pct (%)               1534 non-null   object
 35  Ind_cust_pct (%)               1534 non-null   object
 36  Pc_realgsp_state ($)           1534 non-null   object
 37  Pc_realgsp_usa ($)             1534 non-null   object
 38  Pc_realgsp_rel                 1534 non-null   object
 39  Pc_realgsp_change (%)          1534 non-null   object
 40  Util_realgsp ($)               1534 non-null   object
 41  Total_realgsp ($)              1534 non-null   object
 42  Util_contri (%)                1534 non-null   object
 43  Pi_util_ofusa (%)              1534 non-null   object
 44  Population                     1534 non-null   object
 45  Poppct_urban (%)               1534 non-null   object
 46  Poppct_uc (%)                  1534 non-null   object
 47  Popden_urban (people / sq mi)  1534 non-null   object
 48  Popden_uc (people / sq mi)     1524 non-null   object
 49  Popden_rural (people / sq mi)  1524 non-null   object
 50  Areapct_urban (%)              1534 non-null   object
 51  Areapct_uc (%)                 1534 non-null   object
 52  Pct_land (%)                   1534 non-null   object
 53  Pct_water_tot (%)              1534 non-null   object
 54  Pct_water_inland (%)           1534 non-null   object
dtypes: object(55)
memory usage: 671.1+ KB

In [182]:
df.columns

Index(['Year', 'Month', 'US_state', 'Postal_code', 'Nerc_region', 'Climate_region', 'Anomaly_level', 'Climate_category', 'Outage_start_date', 'Outage_start_time', 'Outage_restoration_date', 'Outage_restoration_time', 'Cause_category', 'Cause_category_detail', 'Hurricane_names', 'Outage_duration', 'Demand_loss_mw', 'Customers_affected', 'Res_price (cents / kWh)', 'Com_price (cents / kWh)', 'Ind_price (cents / kWh)', 'Total_price (cents / kWh)', 'Res_sales', 'Com_sales', 'Ind_sales',
       'Total_sales', 'Res_percen (%)', 'Com_percen (%)', 'Ind_percen (%)', 'Res_customers', 'Com_customers', 'Ind_customers', 'Total_customers', 'Res_cust_pct (%)', 'Com_cust_pct (%)', 'Ind_cust_pct (%)', 'Pc_realgsp_state ($)', 'Pc_realgsp_usa ($)', 'Pc_realgsp_rel', 'Pc_realgsp_change (%)', 'Util_realgsp ($)', 'Total_realgsp ($)', 'Util_contri (%)', 'Pi_util_ofusa (%)', 'Population', 'Poppct_urban (%)', 'Poppct_uc (%)', 'Popden_urban (people / sq mi)', 'Popden_uc (people / sq mi)',
       'Popden_rural (people / sq mi)', 'Areapct_urban (%)', 'Areapct_uc (%)', 'Pct_land (%)', 'Pct_water_tot (%)', 'Pct_water_inland (%)'],
      dtype='object', name=0)

In [183]:
df.dtypes

0
Year                             object
Month                            object
US_state                         object
Postal_code                      object
Nerc_region                      object
Climate_region                   object
Anomaly_level                    object
Climate_category                 object
Outage_start_date                object
Outage_start_time                object
Outage_restoration_date          object
Outage_restoration_time          object
Cause_category                   object
Cause_category_detail            object
Hurricane_names                  object
Outage_duration                  object
Demand_loss_mw                   object
Customers_affected               object
Res_price (cents / kWh)          object
Com_price (cents / kWh)          object
Ind_price (cents / kWh)          object
Total_price (cents / kWh)        object
Res_sales                        object
Com_sales                        object
Ind_sales                        object
Total_sales                      object
Res_percen (%)                   object
Com_percen (%)                   object
Ind_percen (%)                   object
Res_customers                    object
Com_customers                    object
Ind_customers                    object
Total_customers                  object
Res_cust_pct (%)                 object
Com_cust_pct (%)                 object
Ind_cust_pct (%)                 object
Pc_realgsp_state ($)             object
Pc_realgsp_usa ($)               object
Pc_realgsp_rel                   object
Pc_realgsp_change (%)            object
Util_realgsp ($)                 object
Total_realgsp ($)                object
Util_contri (%)                  object
Pi_util_ofusa (%)                object
Population                       object
Poppct_urban (%)                 object
Poppct_uc (%)                    object
Popden_urban (people / sq mi)    object
Popden_uc (people / sq mi)       object
Popden_rural (people / sq mi)    object
Areapct_urban (%)                object
Areapct_uc (%)                   object
Pct_land (%)                     object
Pct_water_tot (%)                object
Pct_water_inland (%)             object
dtype: object

## Step 1: Introduction

## Step 2: Data Cleaning and Exploratory Data Analysis

In [184]:
# TODO
# data cleaning

cleaned_df = df[
    [
        "US_state",
        "Year",
        "Pc_realgsp_state ($)",
        "Outage_start_date",
        "Outage_start_time",
        "Outage_restoration_date",
        "Outage_restoration_time",
        "Total_price (cents / kWh)",
        "Cause_category",
        "Demand_loss_mw",
        "Customers_affected",
        "Total_sales",
    ]
].copy()

cleaned_df["Outage_start_date"] = pd.to_datetime(
    cleaned_df["Outage_start_date"], errors="coerce"
)

cleaned_df["Outage_restoration_date"] = pd.to_datetime(
    cleaned_df["Outage_restoration_date"], errors="coerce"
)


cleaned_df["Outage_start_time"] = pd.to_datetime(
    cleaned_df["Outage_start_time"], format="%H:%M:%S", errors="coerce"
).dt.time

cleaned_df["Outage_restoration_time"] = pd.to_datetime(
    cleaned_df["Outage_restoration_time"], format="%H:%M:%S", errors="coerce"
).dt.time

start = cleaned_df["Outage_start_date"] + pd.to_timedelta(
    cleaned_df["Outage_start_time"].astype(str)
)

end = cleaned_df["Outage_restoration_date"] + pd.to_timedelta(
    cleaned_df["Outage_restoration_time"].astype(str)
)

cleaned_df["Outage_duration"] = (end - start).dt.total_seconds() / 3600

cleaned_df.loc[cleaned_df["Outage_duration"] < 0, "Outage_duration"] = np.nan


cleaned_df = cleaned_df.drop(
    columns=[
        "Outage_start_date",
        "Outage_start_time",
        "Outage_restoration_date",
        "Outage_restoration_time",
    ]
)
print(cleaned_df.head().to_markdown())
# cleaned_df[
#     cleaned_df[["Demand_loss_mw", "Customers_affected", "Demand_loss_mw"]]
#     .isna()
#     .any(axis=1)
# ]

|   Obs | US_state   |   Year |   Pc_realgsp_state ($) |   Total_price (cents / kWh) | Cause_category     |   Demand_loss_mw |   Customers_affected |   Total_sales |   Outage_duration |
|------:|:-----------|-------:|-----------------------:|----------------------------:|:-------------------|-----------------:|---------------------:|--------------:|------------------:|
|     1 | Minnesota  |   2011 |                  51268 |                        9.28 | severe weather     |              nan |                70000 |       6562520 |        51         |
|     2 | Minnesota  |   2014 |                  53499 |                        9.28 | intentional attack |              nan |                  nan |       5284231 |         0.0166667 |
|     3 | Minnesota  |   2010 |                  50447 |                        8.15 | severe weather     |              nan |                70000 |       5222116 |        50         |
|     4 | Minnesota  |   2012 |                  51598 |                        9.19 | severe weather     |              nan |                68200 |       5787064 |        42.5       |
|     5 | Minnesota  |   2015 |                  54431 |                       10.43 | severe weather     |              250 |               250000 |       5970339 |        29         |

In [185]:
fig = px.histogram(
    cleaned_df,
    x="Outage_duration",
    nbins=50,
    title="Distribution of Outage Duration (hours)",
    labels={"Outage_duration": "Outage Duration (hours)"},
)
fig.show()
# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/dist_of_outage_duration.html"
# )

In [186]:
fig = px.histogram(
    cleaned_df,
    x="Pc_realgsp_state ($)",
    nbins=20,
    title="Distribution of Real GSP per State ($)",
)
fig.show()
# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/dist_of_real_GSP_per_state.html"
# )

In [187]:
px.scatter(
    cleaned_df,
    x="Total_price (cents / kWh)",
    y="Outage_duration",
    title="Scatter Plot of Residential Price vs Outage Duration",
    labels={
        "Total_price (cents / kWh)": "Residential Price (cents / kWh)",
        "Outage_duration": "Outage Duration (seconds)",
    },
)

In [188]:
median_df = cleaned_df.groupby("Cause_category", as_index=False)[
    "Outage_duration"
].median()

fig = px.bar(
    median_df,
    x="Cause_category",
    y="Outage_duration",
    title="Median Outage Duration by Cause Category",
    labels={
        "Cause_category": "Cause Category",
        "Outage_duration": "Median Outage Duration (hours)",
    },
    color="Cause_category",
    color_discrete_sequence=px.colors.qualitative.Set3,
)

fig.update_layout(showlegend=False)

fig.show()
fig.write_html(
    "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/median_outage_duration_by_cause.html"
)

In [189]:
import folium
import pandas as pd

state_counts = (
    cleaned_df.groupby("US_state").size().reset_index(name="num_outages")
)

url = "https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/us-states.json"

m1 = folium.Map(location=[37.8, -96], zoom_start=4)

folium.Choropleth(
    geo_data=url,
    data=state_counts,
    columns=["US_state", "num_outages"],
    key_on="feature.properties.name",
    fill_color="YlOrRd",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Number of Power Outages",
).add_to(m1)

m1.save(
    "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/number_of_power_outage.html"
)

In [190]:
state_duration = (
    cleaned_df.groupby("US_state")["Outage_duration"].mean().reset_index()
)

m2 = folium.Map(location=[37.8, -96], zoom_start=4)

folium.Choropleth(
    geo_data=url,
    data=state_duration,
    columns=["US_state", "Outage_duration"],
    key_on="feature.properties.name",
    fill_color="PuBu",
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Average Restoration Time (hours)",
).add_to(m2)

m2.save(
    "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/avg_outage_duration_map.html"
)

In [191]:
# Aggregate analysis
pivot = cleaned_df.pivot_table(
    values="Outage_duration",
    index="Cause_category",
    columns="Year",
    aggfunc="median",
)
print(pivot.to_markdown())

| Cause_category                |      2000 |      2001 |      2002 |      2003 |      2004 |      2005 |     2006 |       2007 |      2008 |      2009 |      2010 |       2011 |      2012 |       2013 |       2014 |       2015 |      2016 |
|:------------------------------|----------:|----------:|----------:|----------:|----------:|----------:|---------:|-----------:|----------:|----------:|----------:|-----------:|----------:|-----------:|-----------:|-----------:|----------:|
| equipment failure             | nan       |   8.23333 | nan       |   2.59167 |   3.68333 |   2.48333 |   2.65   |   3.43333  |   4.48333 |  15.45    |   4.91667 |  0.0666667 |  1.75     |   3.25833  | nan        | nan        | nan       |
| fuel supply emergency         | nan       | nan       | nan       | nan       | nan       | nan       | nan      |  27.9333   | 396       | 109.5     | 168       | 78.75      | 60        |  43.7167   |  93.575    |   4.25     | 568.367   |
| intentional attack            | nan       | nan       | nan       |  22.1583  | nan       | nan       | nan      | nan        | nan       | nan       | nan       |  1.16667   |  0.25     |   1        |   0.15     |   1        |   1.3     |
| islanding                     | nan       | nan       | nan       | nan       | nan       | nan       | nan      |   0.783333 |   3.725   |   4.84167 |   2.03333 |  0.883333  |  0.333333 |   0.533333 |   0.933333 |   0.583333 |   3.71667 |
| public appeal                 | nan       |   2.33333 | nan       |  25.8     |  72       | nan       |   5.95   |  40.5083   | 100.958   |   5       |   8.53333 | 10         |  5        | nan        |   6.7      |   5.55833  | nan       |
| severe weather                |  41.5     | 169       |  86       |  62.2333  |  34.5     |  73.5     |  45.5417 |  25.5      |  53       |  45.1667  |  48.875   | 38.3167    | 41.7833   |  31        |  16.6667   |  32.5      |  23.4167  |
| system operability disruption |   6.25833 |   4.01667 |   3.83333 |  44.9     |   1.58333 |   4.11667 |   3.95   |   6.91667  |   3.24167 |   1.775   |   3.31667 |  4.86667   |  0.216667 |   2.01667  |   0.866667 |   1.08333  |   3.7     |

## Step 3: Assessment of Missingness

In [192]:
# missing values
cleaned_df.isna().sum() / cleaned_df.shape[0]

0
US_state                     0.000000
Year                         0.000000
Pc_realgsp_state ($)         0.000000
Total_price (cents / kWh)    0.014342
Cause_category               0.000000
Demand_loss_mw               0.459583
Customers_affected           0.288787
Total_sales                  0.014342
Outage_duration              0.037810
dtype: float64

In [193]:
cat_cols = ["US_state", "Year", "Cause_category"]
quan_cols = [
    "Pc_realgsp_state ($)",
    "Total_price (cents / kWh)",
    "Demand_loss_mw",
    "Customers_affected",
    "Total_sales",
    "Outage_duration",
]


def missingness_perm_test(df, miss_col, dep_col, test_stat, n_perm=1000):

    # missingness indicator
    missing = df[miss_col].isna()

    # observed statistic
    obs = test_stat(df, missing, dep_col)

    stats = []

    for _ in range(n_perm):

        shuffled = np.random.permutation(missing)

        stat = test_stat(df, shuffled, dep_col)

        stats.append(stat)

    p_value = np.mean(np.array(stats) >= obs)

    return p_value


def tvd_stat(df, missing, dep_col):

    dist = (
        pd.DataFrame({"dep": df[dep_col], "missing": missing})
        .groupby("dep")["missing"]
        .value_counts(normalize=True)
        .unstack(fill_value=0)
    )

    overall = pd.Series(missing).value_counts(normalize=True)

    tvd = 0.5 * np.abs(dist.sub(overall, axis=1)).sum(axis=1).mean()

    return tvd


def diff_mean_stat(df, missing, dep_col):

    return abs(
        df.loc[missing, dep_col].mean() - df.loc[~missing, dep_col].mean()
    )

In [194]:
def helper_missing(test_col):
    for col in cleaned_df.columns:

        if col == test_col or "missing" in col:
            continue

        if col in cat_cols:
            print(
                col,
                missingness_perm_test(
                    cleaned_df,
                    test_col,
                    col,
                    tvd_stat,
                ),
            )

        elif col in quan_cols:
            print(
                col,
                missingness_perm_test(
                    cleaned_df,
                    test_col,
                    col,
                    diff_mean_stat,
                ),
            )

In [195]:
helper_missing("Total_price (cents / kWh)")

US_state 0.0
Year 0.0
Pc_realgsp_state ($) 0.345
Cause_category 0.05
Demand_loss_mw 0.628
Customers_affected 0.247
Total_sales 0.0
Outage_duration 0.083

In [196]:
helper_missing("Demand_loss_mw")

US_state 0.0
Year 0.0
Pc_realgsp_state ($) 0.184
Total_price (cents / kWh) 0.486
Cause_category 0.0
Customers_affected 0.114
Total_sales 0.002
Outage_duration 0.689

In [197]:
# cleaned_df[cleaned_df["Demand_loss_mw"].isna()].sort_values(
#     "Outage_duration"
# ).head(100)

In [198]:
helper_missing("Customers_affected")

US_state 0.0
Year 0.0
Pc_realgsp_state ($) 0.304
Total_price (cents / kWh) 0.481
Cause_category 0.0
Demand_loss_mw 0.0
Total_sales 0.458
Outage_duration 0.016

In [199]:
helper_missing("Total_sales")

US_state 0.0
Year 0.0
Pc_realgsp_state ($) 0.331
Total_price (cents / kWh) 0.0
Cause_category 0.043
Demand_loss_mw 0.638
Customers_affected 0.28
Outage_duration 0.116

In [200]:
helper_missing("Outage_duration")

US_state 0.0
Year 0.0
Pc_realgsp_state ($) 0.973
Total_price (cents / kWh) 0.785
Cause_category 0.0
Demand_loss_mw 0.533
Customers_affected 0.661
Total_sales 0.531

In [201]:
df_plot = cleaned_df.copy()

df_plot["price_missing"] = df_plot["Total_price (cents / kWh)"].isna()

fig = px.histogram(
    df_plot,
    x="Year",
    color="price_missing",
    barmode="group",
    category_orders={"price_missing": [False, True]},
    labels={"price_missing": "Price Missing"},
    title="Missing vs Observed Total_price (cents / kWh) by Year",
)

fig.show()
# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/total_price_missing.html"
# )

In [202]:
missing = cleaned_df["Total_price (cents / kWh)"].isna()

obs_tvd = tvd_stat(cleaned_df, missing, "Year")

perm_stats = []

for _ in range(1000):
    shuffled = pd.Series(np.random.permutation(missing), index=missing.index)
    perm_stats.append(tvd_stat(cleaned_df, shuffled, "Year"))

fig = px.histogram(
    perm_stats,
    nbins=40,
    title="Permutation Distribution of TVD Statistic",
    labels={"value": "TVD"},
)

fig.add_vline(
    x=obs_tvd,
    line_color="red",
    line_width=3,
    annotation_text="Observed TVD",
    annotation_position="top right",
)

fig.update_layout(showlegend=False)

fig.show()

# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/total_price_missing_perm.html"
# )

In [203]:
df_plot["sales_missing"] = df_plot["Total_sales"].isna()

fig = px.histogram(
    df_plot,
    x="Year",
    color="sales_missing",
    barmode="group",
    category_orders={"sales_missing": [False, True]},
    labels={"sales_missing": "Sales Missing"},
    title="Missing vs Observed Total_sales (cents / kWh) by Year",
)

fig.show()
# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/total_sales_missing.html"
# )

In [204]:
missing = cleaned_df["Total_price (cents / kWh)"].isna()

obs_tvd = tvd_stat(cleaned_df, missing, "Year")

perm_stats = []

for _ in range(1000):
    shuffled = pd.Series(np.random.permutation(missing), index=missing.index)
    perm_stats.append(tvd_stat(cleaned_df, shuffled, "Year"))

fig = px.histogram(
    perm_stats,
    nbins=40,
    title="Permutation Distribution of TVD Statistic",
    labels={"value": "TVD"},
)

fig.add_vline(
    x=obs_tvd,
    line_color="red",
    line_width=3,
    annotation_text="Observed TVD",
    annotation_position="top right",
)

fig.update_layout(showlegend=False)

fig.show()

# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/total_sales_missing_perm.html"
# )

In [207]:
# TODO
cleaned_df["Demand_loss_mw"] = cleaned_df.groupby("Cause_category")[
    "Demand_loss_mw"
].transform(lambda x: x.fillna(x.mean()))

# customers affected
cleaned_df["Customers_affected"] = (
    cleaned_df.groupby("US_state")["Customers_affected"]
    .transform(lambda x: x.fillna(x.mean()))
    .fillna(0)
)

# total sales
cleaned_df["Total_sales"] = (
    cleaned_df.groupby("US_state")["Total_sales"]
    .transform(lambda x: x.fillna(x.mean()))
    .fillna(0)
)

cleaned_df["Total_price (cents / kWh)"] = (
    cleaned_df.groupby("US_state")["Total_price (cents / kWh)"]
    .transform(lambda x: x.fillna(x.mean()))
    .fillna(0)
)

# outage duration
cleaned_df["Outage_duration"] = cleaned_df.groupby("Cause_category")[
    "Outage_duration"
].transform(lambda x: x.fillna(x.mean()))

cleaned_df

0         US_state  Year Pc_realgsp_state ($)  Total_price (cents / kWh)         Cause_category  Demand_loss_mw  Customers_affected  Total_sales  Outage_duration
Obs
1        Minnesota  2011                51268                       9.28         severe weather      618.661578        70000.000000    6562520.0        51.000000
2        Minnesota  2014                53499                       9.28     intentional attack        9.151351       124006.571429    5284231.0         0.016667
3        Minnesota  2010                50447                       8.15         severe weather      618.661578        70000.000000    5222116.0        50.000000
4        Minnesota  2012                51598                       9.19         severe weather      618.661578        68200.000000    5787064.0        42.500000
5        Minnesota  2015                54431                      10.43         severe weather      250.000000       250000.000000    5970339.0        29.000000
...            ...   ...                  ...                        ...                    ...             ...                 ...          ...              ...
1530  North Dakota  2011                57012                       7.56          public appeal      155.000000        34500.000000    1313678.0        12.000000
1531  North Dakota  2006                42913                       7.56  fuel supply emergency     1650.000000        34500.000000    1313678.0       224.891667
1532  South Dakota  2009                45230                       7.67              islanding       84.000000            0.000000     924051.0         0.983333
1533  South Dakota  2009                45230                       7.67              islanding      373.000000            0.000000     924051.0         3.016667
1534        Alaska  2000                57401                       0.00      equipment failure       35.000000        14273.000000          0.0        30.300000

[1534 rows x 9 columns]

In [208]:
cleaned_df.isna().sum()

0
US_state                     0
Year                         0
Pc_realgsp_state ($)         0
Total_price (cents / kWh)    0
Cause_category               0
Demand_loss_mw               0
Customers_affected           0
Total_sales                  0
Outage_duration              0
dtype: int64

In [144]:
cleaned_df[cleaned_df["Customers_affected"].isna()]

Empty DataFrame
Columns: [US_state, Year, Pc_realgsp_state ($), Total_price (cents / kWh), Cause_category, Demand_loss_mw, Customers_affected, Total_sales, Outage_duration]
Index: []

In [145]:
cleaned_df[
    (cleaned_df["US_state"] == "Montana")
    | (cleaned_df["US_state"] == "South Dakota")
]

0         US_state  Year Pc_realgsp_state ($)  Total_price (cents / kWh)      Cause_category  Demand_loss_mw  Customers_affected  Total_sales  Outage_duration
Obs
917        Montana  2014                38820                       8.70           islanding      396.564103                 0.0    1242527.0         0.933333
918        Montana  2013                38395                       8.75  intentional attack        9.151351                 0.0    1059449.0         1.550000
919        Montana  2010                37156                       7.68           islanding      396.564103                 0.0    1050775.0         0.216667
1532  South Dakota  2009                45230                       7.67           islanding       84.000000                 0.0     924051.0         0.983333
1533  South Dakota  2009                45230                       7.67           islanding      373.000000                 0.0     924051.0         3.016667

## Step 4: Hypothesis Testing

In [146]:
df_hypo_h0 = cleaned_df[["Pc_realgsp_state ($)", "Outage_duration"]].copy()
df_hypo_h0["Pc_realgsp_state ($)"] = (
    df_hypo_h0["Pc_realgsp_state ($)"] >= 50000
)

group_medians = df_hypo_h0.groupby("Pc_realgsp_state ($)")[
    "Outage_duration"
].median()

test_stat = abs(group_medians.loc[True] - group_medians.loc[False])
arr = []

for _ in range(1000):
    shuffled = np.random.permutation(df_hypo_h0["Pc_realgsp_state ($)"])
    tmp = df_hypo_h0.copy()
    tmp["shuffle"] = shuffled
    tmp_medians = tmp.groupby("shuffle")["Outage_duration"].median()
    arr.append(abs(tmp_medians.loc[True] - tmp_medians.loc[False]))

arr = np.array(arr)
p_value = np.mean(arr >= test_stat)

p_value

np.float64(0.0)

In [147]:
import plotly.graph_objects as go

fig = go.Figure()

# histogram of permutation statistics
fig.add_trace(
    go.Histogram(
        x=arr, nbinsx=40, name="Permutation distribution", opacity=0.75
    )
)

# vertical line for observed statistic
fig.add_vline(
    x=test_stat,
    line_color="red",
    line_width=3,
    annotation_text=f"Observed stat = {test_stat:.2f}",
    annotation_position="top",
)

fig.update_layout(
    title="Permutation Test Distribution",
    xaxis_title="Difference in Median Outage Duration",
    yaxis_title="Count",
    showlegend=False,
)

fig.show()

# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/perm_test_dist.html"
# )

In [148]:
fig = px.histogram(
    df_hypo_h0,
    x="Outage_duration",
    color="Pc_realgsp_state ($)",
    barmode="overlay",
    histnorm="percent",
)

fig.update_traces(opacity=0.6)
fig.show()

# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/outage_duration_with_labels.html"
# )

In [149]:
df_hypo_h0 = cleaned_df[["Pc_realgsp_state ($)", "Outage_duration"]]
df_hypo_h0.head()
df_norm = df_hypo_h0.copy()

for col in df_norm.columns:
    df_norm[col] = (df_norm[col] - np.mean(df_norm[col])) / (
        np.std(df_norm[col])
    )

fig = px.histogram(
    df_norm.melt(var_name="variable", value_name="value"),
    x="value",
    color="variable",
    barmode="overlay",
    histnorm="percent",
)

fig.show()

## Step 5: Framing a Prediction Problem

In [150]:
# TODO

In [151]:
cleaned_df["Outage_duration"].mean()

np.float64(43.75460704607046)

## Step 6: Baseline Model

In [152]:
# TODO
X = cleaned_df[
    [
        "Pc_realgsp_state ($)",
        "Total_price (cents / kWh)",
        "Cause_category",
        "Demand_loss_mw",
        "Customers_affected",
        "Total_sales",
    ]
]

y = np.log1p(cleaned_df["Outage_duration"])

cat_cols = ["Cause_category"]

num_cols = [
    "Pc_realgsp_state ($)",
    "Total_price (cents / kWh)",
    "Demand_loss_mw",
    "Customers_affected",
    "Total_sales",
]

preprocessor = make_column_transformer(
    (OneHotEncoder(handle_unknown="ignore"), cat_cols),
    (StandardScaler(), num_cols),
    remainder="passthrough",
)


pl = make_pipeline(
    preprocessor,
    # RandomForestRegressor(
    #     n_estimators=500, min_samples_leaf=3, max_depth=None, random_state=42
    # ),
    LinearRegression(),  # RandomForestRegressor(n_estimators=300, random_state=42)
    # GradientBoostingRegressor(
    #     loss="absolute_error",  # <-- MAE training
    #     n_estimators=300,
    #     random_state=42,
    # ),
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pl.fit(X_train, y_train)
pred = pl.predict(X_test)

rmse_log = np.sqrt(mean_squared_error(y_test, pred))
# mae = mean_absolute_error(y_test, pred)


pred_original = np.expm1(pred)
y_test_original = np.expm1(y_test)

# RMSE in original scale
rmse_original = np.sqrt(mean_squared_error(y_test_original, pred_original))
# mae_original = mean_absolute_error(y_test_original, pred_original)

rmse_log, rmse_original
# mae, mae_original

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [42]:
X_train

0    Pc_realgsp_state ($)  Total_price (cents / kWh)                 Cause_category  Demand_loss_mw  Customers_affected  Total_sales
Obs
263                 46396                       7.27                 severe weather      300.000000        63000.000000   23378775.0
1150                51424                      11.41                 severe weather      240.000000       505000.000000   17876563.0
691                 44413                       6.87                 severe weather      177.000000       127000.000000   12091413.0
837                 48323                       8.34             intentional attack        9.564972        43958.583333    3641613.0
741                 42746                       8.97                 severe weather        3.000000         1200.000000   10625020.0
...                   ...                        ...                            ...             ...                 ...          ...
1170                51733                      12.18  system operability disruption      324.000000       195413.520661   20861122.0
1344                52093                       8.37                 severe weather      613.708763        50000.000000    8899503.0
894                 62327                      10.96             intentional attack        0.000000            0.000000     829672.0
1515                42502                       5.88                 severe weather      200.000000       211000.000000    3190147.0
1166                54713                      13.62              equipment failure      240.000000       195413.520661   26288469.0

[1180 rows x 6 columns]

In [43]:
y_pred = pl.predict(X_test)
plot_df = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})
fig = px.scatter(
    plot_df,
    x="Actual",
    y="Predicted",
    title="Predicted vs Actual Outage Duration (Logarithmic Scale)",
    labels={
        "Actual": "Actual Outage Duration",
        "Predicted": "Predicted Outage Duration",
    },
)

fig.show()

# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/baseline_log.html"
# )

In [44]:
# predicted vs actual outage duration after retransformation
y_pred = pl.predict(X_test)

# Convert back to original scale
y_test_original = np.expm1(y_test)
y_pred_original = np.expm1(y_pred)

plot_df = pd.DataFrame(
    {"Actual": y_test_original, "Predicted": y_pred_original}
)

fig = px.scatter(
    plot_df,
    x="Actual",
    y="Predicted",
    title="Predicted vs Actual Outage Duration (Original Scale)",
    labels={
        "Actual": "Actual Outage Duration",
        "Predicted": "Predicted Outage Duration",
    },
)

fig.show()

# fig.write_html(
#     "/Users/wuyuming/Desktop/proj_4/proj04_page/graph/baseline_original_scale.html"
# )

In [45]:
cleaned_df["Outage_duration"].quantile(
    [0.25, 0.5, 0.6, 0.7, 0.75, 0.8, 0.9, 0.95, 0.99, 0.995, 0.999, 0.9999, 1]
)
# cleaned_df["Outage_duration"].sort_values(ascending=False).iloc[:20]

0.2500       1.704167
0.5000      11.683333
0.6000      22.866667
0.7000      39.750000
0.7500      48.000000
0.8000      60.000000
0.9000     114.616667
0.9500     185.212500
0.9900     388.837500
0.9950     534.291667
0.9990    1165.598750
0.9999    1737.454833
1.0000    1811.883333
Name: Outage_duration, dtype: float64

In [46]:
cleaned_df["Outage_duration"].mean()

np.float64(43.75460704607046)

## Step 7: Final Model

In [47]:
# TODO
third_qrt = cleaned_df["Outage_duration"].quantile(0.75)
first_qrt = cleaned_df["Outage_duration"].quantile(0.25)
bound = 1.5 * (third_qrt - first_qrt)
no_outliers = cleaned_df[cleaned_df["Outage_duration"] <= third_qrt + bound]

# TODO
X = no_outliers[
    [
        "Pc_realgsp_state ($)",
        "Total_price (cents / kWh)",
        "Cause_category",
        "Demand_loss_mw",
        "Customers_affected",
        "Total_sales",
    ]
]

y = np.log1p(no_outliers["Outage_duration"])

# final_df = cleaned_df.copy()

# final_df["price_income_ratio"] = (
#     final_df["Total_price (cents / kWh)"] / final_df["Pc_realgsp_state ($)"]
# )

# final_df["Demand_loss_mw"] = np.log1p(final_df["Demand_loss_mw"])
# final_df["Customers_affected"] = np.log1p(final_df["Customers_affected"])


# X = final_df[
#     [
#         "Pc_realgsp_state ($)",
#         "Total_price (cents / kWh)",
#         "Cause_category",
#         "Demand_loss_mw",
#         "Customers_affected",
#         "Total_sales",
#         "price_income_ratio",
#     ]
# ]

# y = np.log1p(final_df["Outage_duration"])


num_cols = [
    "Pc_realgsp_state ($)",
    "Total_price (cents / kWh)",
    "Demand_loss_mw",
    "Customers_affected",
    "Total_sales",
    # "price_income_ratio",
]

preprocessor = make_column_transformer(
    (OneHotEncoder(handle_unknown="ignore"), cat_cols),
    (StandardScaler(), num_cols),
)

pl = make_pipeline(
    preprocessor,
    RandomForestRegressor(random_state=42),
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

param_grid = {
    "randomforestregressor__n_estimators": [100, 200, 300, 400, 500],
    "randomforestregressor__max_depth": [5, 10, 15, None],
    "randomforestregressor__min_samples_leaf": [1, 3, 5, 10],
}

grid = GridSearchCV(pl, param_grid, cv=5)
grid.fit(X_train, y_train)

best_model = grid.best_estimator_

pred = best_model.predict(X_test)

rmse_log = np.sqrt(mean_squared_error(y_test, pred))

pred_original = np.expm1(pred)
y_test_original = np.expm1(y_test)

rmse_original = np.sqrt(mean_squared_error(y_test_original, pred_original))

rmse_log, rmse_original

(np.float64(1.091879226983468), np.float64(22.571435494322717))

In [48]:
X_train

0    Pc_realgsp_state ($)  Total_price (cents / kWh)      Cause_category  Demand_loss_mw  Customers_affected  Total_sales
Obs
1474                47697                      14.65  intentional attack        0.000000            0.000000     985109.0
676                 42521                       7.77  intentional attack        0.000000            0.000000    2492126.0
1131                53092                      10.85      severe weather      120.000000       442000.000000   20470914.0
488                 53622                       7.06  intentional attack        9.564972        93172.026316    8988060.0
201                 44959                       7.26   equipment failure      212.000000        68530.000000   22746099.0
...                   ...                        ...                 ...             ...                 ...          ...
1279                53487                      14.64  intentional attack        9.564972       195413.520661   22151808.0
1317                51480                       9.50      severe weather      613.708763        52739.000000   10600512.0
1489                43209                       8.84  intentional attack        9.564972        22220.000000    2727874.0
1008                45813                       7.48   equipment failure       33.000000        11000.000000    6236365.0
1313                52093                       9.46      severe weather        0.000000            0.000000   10355383.0

[1065 rows x 6 columns]

In [49]:
y_pred = best_model.predict(X_test)
plot_df = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})
fig = px.scatter(
    plot_df,
    x="Actual",
    y="Predicted",
    title="Predicted vs Actual Outage Duration",
    labels={
        "Actual": "Actual Outage Duration",
        "Predicted": "Predicted Outage Duration",
    },
)

fig.show()

In [50]:
# predicted vs actual outage duration after retransformation
y_pred = best_model.predict(X_test)

# Convert back to original scale
y_test_original = np.expm1(y_test)
y_pred_original = np.expm1(y_pred)

plot_df = pd.DataFrame(
    {"Actual": y_test_original, "Predicted": y_pred_original}
)

fig = px.scatter(
    plot_df,
    x="Actual",
    y="Predicted",
    title="Predicted vs Actual Outage Duration (Original Scale)",
    labels={
        "Actual": "Actual Outage Duration",
        "Predicted": "Predicted Outage Duration",
    },
)

fig.show()

In [51]:
final_df["Outage_duration"].mean()

NameError: name 'final_df' is not defined

## Step 8: Fairness Analysis

In [799]:
# TODO